"""Initial migration

Revision ID: 0689c89de188
Revises: 
Create Date: 2022-04-25 14:08:04.820865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0689c89de188"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("test", sa.Text(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "created_timestamp",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("test"),
    )
    op.create_table(
        "test_run",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_timestamp",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assertion",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("json_path", sa.Text(), nullable=False),
        sa.Column("regex", sa.Text(), nullable=False),
        sa.Column("test_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.test"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "result",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("actual", sa.Text(), nullable=True),
        sa.Column("match", sa.BOOLEAN(), nullable=True),
        sa.Column("test_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("test_id", sa.Text(), nullable=True),
        sa.Column(
            "created_timestamp",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.test"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_runs",
        sa.Column("test_id", sa.Text(), nullable=True),
        sa.Column("test_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.test"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_runs")
    op.drop_table("result")
    op.drop_table("assertion")
    op.drop_table("test_run")
    op.drop_table("test")
    # ### end Alembic commands ###
