"""add assertion type for strict and warning checks. Strict is pass/fail, warning is for less important discrepancies

Revision ID: b8670422db69
Revises: c6e76ab376a8
Create Date: 2022-05-12 10:09:10.997732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import orm
from sqlalchemy.dialects import postgresql

from application.models import AssertionType

revision = "b8670422db69"
down_revision = "c6e76ab376a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    assertion_type = postgresql.ENUM(AssertionType, name="assertion_type")
    assertion_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "assertion",
        sa.Column(
            "assertion_type", sa.Enum("strict", "warning", name="assertion_type")
        ),
    )
    op.execute("UPDATE assertion SET assertion_type = 'strict'")
    op.alter_column("assertion", "assertion_type", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assertion", "assertion_type")
    # ### end Alembic commands ###
