"""Add ticket to test

Revision ID: feb61bb60196
Revises: 0689c89de188
Create Date: 2022-04-26 17:07:38.909809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb61bb60196'
down_revision = '0689c89de188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('ticket', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'ticket')
    # ### end Alembic commands ###
